In [27]:
import numpy as np
from sklearn import linear_model
import pandas as pd

df = pd.read_csv('D:\Documents\hiring_data.csv')
df

experience  test_score  interview_score  salary
0         NaN         8.0                9   50000
1         NaN         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [28]:
# finding the median...
s=df.test_score.median()
s

8.0

In [29]:
#fill the null value of the  test_score.........
df.test_score = df.test_score.fillna(s)
df

experience  test_score  interview_score  salary
0         NaN         8.0                9   50000
1         NaN         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         8.0                7   72000
7        11.0         7.0                8   80000

In [56]:
# finding the median..
e=df.experience.median()
e

7.5

In [57]:
#median_bedroom=math.floor(df.bedroom.median())
#median_bedroom
#fill the null value of the  test_score.........
#import math
#me = math.floor(df.experience.fillna(e))
#me
df.experience = df.experience.fillna(e)
df

experience  test_score  interview_score  salary
0         8.0         8.0                9   50000
1         8.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         8.0                7   72000
7        11.0         7.0                8   80000

In [58]:
# independent_factor_['experience','test_score','interview_score']
#dependent_factor_['salary']
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [45]:
#function
reg.coef_

array([1446.40832732,  620.63279398, 1755.02421931])

In [46]:
#function
reg.intercept_

34528.444810883244

In [55]:
#prediction of ['2_year_experience','9_test_score','6_interview_score']
reg.predict([[2,9,6]])

array([53537.10192724])

In [37]:
[1446.40832732*2+ 620.63279398*9+ 1755.02421931*6+34528.444810883244]

[53537.10192720324]

In [40]:
reg.coef_

array([1446.40832732,  620.63279398, 1755.02421931])

In [39]:
#prediction of ['12_year_experience','10_test_score','10_interview_score']
reg.predict([[12,10,10]])

array([75641.91487169])